// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_CFWxYFLcm2-nexMrLRhq5FjjjUXNN0',
    appId: '1:222684214362:web:2a97e62009e86f3f3f5463',
    messagingSenderId: '222684214362',
    projectId: 'chat-app-4efe4',
    authDomain: 'chat-app-4efe4.firebaseapp.com',
    storageBucket: 'chat-app-4efe4.appspot.com',
    measurementId: 'G-WM2WVF05ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVee36kVhLKb-Y-8aFlxZ5D3Vzz715Xus',
    appId: '1:222684214362:android:2cdb2bd55fb74ea83f5463',
    messagingSenderId: '222684214362',
    projectId: 'chat-app-4efe4',
    storageBucket: 'chat-app-4efe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JYBcgwuTWxEGl3D9SGnYFCQFlaIYbsI',
    appId: '1:222684214362:ios:f7686ef3f73131ef3f5463',
    messagingSenderId: '222684214362',
    projectId: 'chat-app-4efe4',
    storageBucket: 'chat-app-4efe4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3JYBcgwuTWxEGl3D9SGnYFCQFlaIYbsI',
    appId: '1:222684214362:ios:f7686ef3f73131ef3f5463',
    messagingSenderId: '222684214362',
    projectId: 'chat-app-4efe4',
    storageBucket: 'chat-app-4efe4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH_CFWxYFLcm2-nexMrLRhq5FjjjUXNN0',
    appId: '1:222684214362:web:608d1bc45e2576d03f5463',
    messagingSenderId: '222684214362',
    projectId: 'chat-app-4efe4',
    authDomain: 'chat-app-4efe4.firebaseapp.com',
    storageBucket: 'chat-app-4efe4.appspot.com',
    measurementId: 'G-MNGX9NL0B0',
  );
}
